Remove outdated integration step for nRF Connect SDK
Got this during compilation:

```bash
(.venv)  ~/Development/memfault-nRF9160-relay => west build -b=qemu_x86_64 firmware
Including boilerplate (Zephyr base (cached)): /home/fausto/Development/memfault-nRF9160-relay/zephyr/cmake/app/boilerplate.cmake
[0/1] Re-running CMake...
-- Application: /home/fausto/Development/memfault-nRF9160-relay/firmware
-- Zephyr version: 2.4.99 (/home/fausto/Development/memfault-nRF9160-relay/zephyr)
-- Found west (found suitable version "0.11.0", minimum required is "0.7.1")
CMake Error at /home/fausto/Development/memfault-nRF9160-relay/zephyr/cmake/zephyr_module.cmake:61 (message):
  zephyr/../modules/memfault-firmware-sdk/ports/nrf-connect-sdk, given in
  ZEPHYR_EXTRA_MODULES, is not a valid zephyr module

Call Stack (most recent call first):
  /home/fausto/Development/memfault-nRF9160-relay/zephyr/cmake/app/boilerplate.cmake:183 (include)
  /home/fausto/Development/memfault-nRF9160-relay/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  /home/fausto/Development/memfault-nRF9160-relay/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:40 (include_boilerplate)
  CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/fausto/Development/memfault-nRF9160-relay/build/CMakeFiles/CMakeOutput.log".
See also "/home/fausto/Development/memfault-nRF9160-relay/build/CMakeFiles/CMakeError.log".
FAILED: build.ninja
/home/fausto/Development/memfault-nRF9160-relay/.venv/lib/python3.9/site-packages/cmake/data/bin/cmake --regenerate-during-build -S/home/fausto/Development/memfault-nRF9160-relay/firmware -B/home/fausto/Development/memfault-nRF9160-relay/build
ninja: error: rebuilding 'build.ninja': subcommand failed
FATAL ERROR: command exited with status 1: /home/fausto/Development/memfault-nRF9160-relay/.venv/bin/cmake --build /home/fausto/Development/memfault-nRF9160-relay/build
```

@chris pointed out to me that removing the lines would fix it. So I'm
removing it from the docs, too.